### PR TITLE
Added oob_ip field to Device

### LINKED ISSUE #129: Support for Device OOB IP
For a years NetBox users requested for OOB IP in DCIM https://github.com/netbox-community/netbox/issues/8137
Now this PR merged and will avail in NetBox 3.6 https://github.com/netbox-community/netbox/pull/13013

`netbox-plugin-prometheus-sd` shoud have `oob_ip` field accordingly

### PR DESCRIPTION
**Pull request by k0ste**
Fixes #129

### CODE REVIEW

**Comment by k0ste** [comment]
@FlxPeters please run CI tests
Stuck with local tests, due some errors

```
example-netbox-1       | django.core.exceptions.ImproperlyConfigured: Plugin netbox_initializers requires NetBox minimum version 3.5.0.
example-netbox-1       | ❌ Waited 30s or more for the DB to become ready.
example-netbox-1 exited with code 1
```

Then I bump NetBox container version to 3.6
```
example-netbox-1       | 🧬 loaded config '/etc/netbox/config/configuration.py'
example-netbox-1       | 🧬 loaded config '/etc/netbox/config/extra.py'
example-netbox-1       | 🧬 loaded config '/etc/netbox/config/logging.py'
example-netbox-1       | 🧬 loaded config '/etc/netbox/config/plugins.py'
example-netbox-1       | Traceback (most recent call last):
example-netbox-1       |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
example-netbox-1       |     execute_from_command_line(sys.argv)
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
example-netbox-1       |     utility.execute()
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
example-netbox-1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
example-netbox-1       |     self.execute(*args, **cmd_options)
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 453, in execute
example-netbox-1       |     self.check()
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
example-netbox-1       |     all_issues = checks.run_checks(
example-netbox-1       |                  ^^^^^^^^^^^^^^^^^^
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
example-netbox-1       |     new_errors = check(app_configs=app_configs, databases=databases)
example-netbox-1       |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/checks/caches.py", line 17, in check_default_cache_is_configured
example-netbox-1       |     if DEFAULT_CACHE_ALIAS not in settings.CACHES:
example-netbox-1       |                                   ^^^^^^^^^^^^^^^
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
example-netbox-1       |     self._setup(name)
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
example-netbox-1       |     self._wrapped = Settings(settings_module)
example-netbox-1       |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
example-netbox-1       |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
example-netbox-1       |     mod = importlib.import_module(self.SETTINGS_MODULE)
example-netbox-1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
example-netbox-1       |   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
example-netbox-1       |     return _bootstrap._gcd_import(name[level:], package, level)
example-netbox-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
example-netbox-1       |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
example-netbox-1       |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
example-netbox-1       |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
example-netbox-1       |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
example-netbox-1       |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
example-netbox-1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
example-netbox-1       |   File "/opt/netbox/netbox/netbox/settings.py", line 75, in <module>
example-netbox-1       |     raise ImproperlyConfigured(
example-netbox-1       | django.core.exceptions.ImproperlyConfigured: SECRET_KEY must be at least 50 characters in length. To generate a suitable key, run the following command:
example-netbox-1       |   python /opt/netbox/netbox/generate_secret_key.py
```

Like for me the `SECRET_KEY` exactly 50 symbols length 🤷‍♂️

**Comment by k0ste** [comment]
Ping @FlxPeters

**Comment by FlxPeters** [comment]
Tests are on their way. I will release a new version with 3.6 compatibility soon. 
If this feature is ready we can release a new version with this included directly after.

**Comment by k0ste** [comment]
> Tests are on their way. I will release a new version with 3.6 compatibility soon.
> If this feature is ready we can release a new version with this included directly after.
Seems tests passed, if you prepare release our devops can start updating prod containers

**Comment by FlxPeters** [comment]
I just merged it, let me know if it works for you from the latest master, than I will create a new release

**Comment by 33Fraise33** [comment]
Hi @FlxPeters any plan to release this feature in a new version?

**Comment by FlxPeters** [comment]
Yes, I will make a release soon.

**Pull request merged**
