### PR TITLE
Add site and site_slug labels to device services

### PR DESCRIPTION
**Pull request by jkrcma**
## Describe your changes

Hello,

when developing an internal Service Discovery framework I found out that Netbox devices do not necessarily have the _Site_ label present. When digging I found out that the condition applies only to devices without _Cluster_ set. I've made this PR to prioritize locally configured _Site_ of the device object, instead of _Rack_ or _Cluster_. Given how loose the constraints in Netbox database are, I might have missed something. Let me know please!

## Issue ticket number and link

None.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by FlxPeters** [comment]
@jkrcma tests seem to be broken. Can you please check and fix this? 
I agree with the change at all, so if the build is green we can move forward.

**Comment by jkrcma** [comment]
Looks like a consequence of the change I did in b40f30ebadffc5811afd1cc438406f77a6010b7d. Despite using Docker I wasn't able to make tests running on my local laptop without that commit. Thanks for the CI output, I will dig in it.

**Comment by jkrcma** [comment]
Alright, figured out. I did a mistake in the first step of delegating the venv to poetry itself. I apologize, haven't worked with it much lately :slightly_smiling_face:

**Comment by jkrcma** [comment]
Done, let me know if you have any suggestion for the scope of the `feat` one. I was thinking of `api` or `services`, but I chose to not specify it at all.

**Pull request merged**
