### PR TITLE
Feature: Add new label "custom_field_data"

### PR DESCRIPTION
**Pull request by oijkn**
Add new query with iregex search and add custom_fields data to the return.

**Example route :**
https://netbox.com/api/plugins/prometheus-sd/devices/?deviceModel=d.*nk -> this _iregex_ can return all "dlink" models

### CODE REVIEW

**Comment by FlxPeters** [comment]
I like the idea of having regex as possible filter values. This only works for device types now, right? Is there a generic way to make this available for all filters?

**Comment by oijkn** [comment]
As requested I removed the changes on the view and kept only the custom fields in the Prometheus labels.

For the unit tests, I prefer to let you code them yourself as I'm not familiar with them.

Regular expression filters only work with the `/devices` route.
To make this function generic, you should certainly use the `get_queryset` function on the other views, no?

**Comment by FlxPeters** [comment]
Ok, I'm back from vacation next week and will spend some time on this project. So I can add the tests and maybe also fix the regex issue.
When it's done I will release a new version.

**Comment by oijkn** [comment]
Ok great, thanks in advance.

Could you also add a feature to display a limit + offset, like in the basic API ?

Example : https://netbox.com/api/dcim/devices/?limit=50&offset=50

**Comment by FlxPeters** [comment]
Closing in favor of #73

**Pull request closed without merging**
