### PR TITLE
Expose primary keys in labels

### PR DESCRIPTION
**Pull request by jsenecal**
Allows direct links to netbox things from dashboards exposing these metrics.

### CODE REVIEW

**Comment by FlxPeters** [comment]
Thanks for your contribution. Can you please add the field to the tests? 
As soon as we have a test i will merge it.

**Comment by jsenecal** [comment]
> Thanks for your contribution. Can you please add the field to the tests? As soon as we have a test i will merge it.

I will try to update my pr to include the new field in the tests. However, I'm unable to run them for variou reasons, It seems like the toolkit is currently incompatible with the current version of netbox (postgresql, timezones, etc)

**Comment by jsenecal** [comment]
@FlxPeters is there anything else missing to merge this pull request ?

**Comment by FlxPeters** [comment]
Sorry for the delay, i had to fix the tests first. 
Version 0.6.1 is out with this feature merged.

**Pull request merged**
